services:
  - type: web
    name: phub-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: /data/phub.db
